server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    de.freitag.stefan.ledborg.rest: INFO

  appenders:
     - type: console
     - type: file
       threshold: all
       logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
       currentLogFilename: ./log/ledborg-rest.log
       archivedLogFilenamePattern: ./log/ledborg-rest.log-%d{yyyy-MM-dd}-%i.log.gz
       archivedFileCount: 7
       maxFileSize: 100MB
       timeZone: UTC
